name: audioplayers
description: A flutter plugin to play multiple audio files simultaneously
version: 0.14.1
homepage: https://github.com/luanpotter/audioplayer

flutter:
  plugin:
    platforms:
      android:
        package: xyz.luan.audioplayers
        pluginClass: AudioplayersPlugin
      ios:
        pluginClass: AudioplayersPlugin
      macos:
        pluginClass: AudioplayersPlugin
      web:
        pluginClass: AudioplayersPlugin
        fileName: audioplayers_web.dart

dependencies:
  uuid: ^2.0.4
  path_provider: ^1.6.5
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  http: ^0.12.0+4
environment:
  sdk: ">=2.7.0 <3.0.0"


